services:
  sendmemail:
    hostname: webserver
    build:
      context: ./SendMeMail
    ports:
      - 8088:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
  smtpserver:
    hostname: smtpserver
    ports:
      - 8085:1080
    image: maildev/maildev